/* Generated By:JJTree: Do not edit this line. ASTA_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTA_list extends SimpleNode {
  public ASTA_list(int id) {
    super(id);
  }

  public ASTA_list(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d63b404d0ae53e9c6fd628a56c36f2cc (do not edit this line) */
