/* Generated By:JJTree: Do not edit this line. ASTA_List2.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTA_List2 extends SimpleNode {
  public ASTA_List2(int id) {
    super(id);
  }

  public ASTA_List2(Dot2Dot p, int id) {
    super(p, id);
  }

  public String toString() { return value.toString(); }
}
/* JavaCC - OriginalChecksum=2f4074cb71c2de862fb883cdc6e52432 (do not edit this line) */
