/* Generated By:JJTree: Do not edit this line. ASTAttr_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAttr_list extends SimpleNode {
  public ASTAttr_list(int id) {
    super(id);
  }

  public ASTAttr_list(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a823111141a74cb3804b06e2be53714c (do not edit this line) */
