/* Generated By:JJTree: Do not edit this line. ASTAttr_smt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAttr_smt extends SimpleNode {
  public ASTAttr_smt(int id) {
    super(id);
  }

  public ASTAttr_smt(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3feddaa7a63f98084d6aae32572200e6 (do not edit this line) */
