/* Generated By:JJTree: Do not edit this line. ASTCenas.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCenas extends SimpleNode {
  public ASTCenas(int id) {
    super(id);
  }

  public ASTCenas(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e17f301b50fdc0f4375f4cd3b17041a (do not edit this line) */
