/* Generated By:JJTree: Do not edit this line. ASTDotGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDotGraph extends SimpleNode {
  public ASTDotGraph(int id) {
    super(id);
  }

  public ASTDotGraph(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37892a8c32a29f5a5f58f258f817c17c (do not edit this line) */
