/* Generated By:JJTree: Do not edit this line. ASTEdgeOP.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEdgeOP extends SimpleNode {
  public ASTEdgeOP(int id) {
    super(id);
  }

  public ASTEdgeOP(Dot2Dot p, int id) {
    super(p, id);
  }

  public String toString() { return (String) value; }
}
/* JavaCC - OriginalChecksum=9a526a50e94f7dd09a5322498bdd59b9 (do not edit this line) */
