/* Generated By:JJTree: Do not edit this line. ASTEdge_stmt_temp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEdge_stmt_temp extends SimpleNode {
  public ASTEdge_stmt_temp(int id) {
    super(id);
  }

  public ASTEdge_stmt_temp(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b30fed738d1323d114b9a9924ad4ad2d (do not edit this line) */
