/* Generated By:JJTree: Do not edit this line. ASTEdgeRHS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEdgeRHS extends SimpleNode {
  public ASTEdgeRHS(int id) {
    super(id);
  }

  public ASTEdgeRHS(Dot2Dot p, int id) {
    super(p, id);
  }

  public String toString() { return value.toString(); }
  
}
/* JavaCC - OriginalChecksum=bd79d5ad454091b039b132a41b948b51 (do not edit this line) */
