/* Generated By:JJTree: Do not edit this line. ASTEdge.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEdge extends SimpleNode {
  public ASTEdge(int id) {
    super(id);
  }

  public ASTEdge(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce376e7e8a8efe2cc408a92ba827c2be (do not edit this line) */
