/* Generated By:JJTree: Do not edit this line. ASTEdge_stmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEdge_stmt extends SimpleNode {
  public ASTEdge_stmt(int id) {
    super(id);
  }

  public ASTEdge_stmt(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7150ab8ab537fda53a284ecc0b743da2 (do not edit this line) */
