/* Generated By:JJTree: Do not edit this line. ASTGraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGraph extends SimpleNode {
  public ASTGraph(int id) {
    super(id);
  }

  public ASTGraph(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=136071535166a3e0a5cd8e6c85efe1d5 (do not edit this line) */
