/* Generated By:JJTree: Do not edit this line. ASTNova.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNova extends SimpleNode {
  public ASTNova(int id) {
    super(id);
  }

  public ASTNova(Dot2Dot p, int id) {
    super(p, id);
  }

  public String toString() { return value.toString(); }

}
/* JavaCC - OriginalChecksum=c2295d82a16d35056fb973883534afd1 (do not edit this line) */
