/* Generated By:JJTree: Do not edit this line. ASTNode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNode extends SimpleNode {
  public ASTNode(int id) {
    super(id);
  }

  public ASTNode(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6b8325322bc958efce4d75e03680168 (do not edit this line) */
