/* Generated By:JJTree: Do not edit this line. ASTNode_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNode_id extends SimpleNode {
  public ASTNode_id(int id) {
    super(id);
  }

  public ASTNode_id(Dot2Dot p, int id) {
    super(p, id);
  }

  public String toString() { return value.toString(); }
  
}
/* JavaCC - OriginalChecksum=997b293ada5ff75a1072e8312f27640c (do not edit this line) */
