/* Generated By:JJTree: Do not edit this line. ASTno.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTno extends SimpleNode {
  public ASTno(int id) {
    super(id);
  }

  public ASTno(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fcb76af7a0436a0e9947c10b2fc9372c (do not edit this line) */
