/* Generated By:JJTree: Do not edit this line. ASToperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASToperator extends SimpleNode {
  public ASToperator(int id) {
    super(id);
  }

  public ASToperator(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42edaaabc66dd0275e7cf88927c5c631 (do not edit this line) */
