/* Generated By:JJTree: Do not edit this line. ASTPort.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPort extends SimpleNode {
  public ASTPort(int id) {
    super(id);
  }

  public ASTPort(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79183c3cfbb586c9d7c112ac85fd3f2a (do not edit this line) */
