/* Generated By:JJTree: Do not edit this line. ASTStupid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStupid extends SimpleNode {
  public ASTStupid(int id) {
    super(id);
  }

  public ASTStupid(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8dd054caa1eae8ebac160cde4ae4e48 (do not edit this line) */
