/* Generated By:JJTree: Do not edit this line. ASTSubgraph.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSubgraph extends SimpleNode {
  public ASTSubgraph(int id) {
    super(id);
  }

  public ASTSubgraph(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92e8f0cc8f75ef7c619f01347cacde47 (do not edit this line) */
