/* Generated By:JJTree: Do not edit this line. ASTStmt_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmt_list extends SimpleNode {
  public ASTStmt_list(int id) {
    super(id);
  }

  public ASTStmt_list(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4dc76c65daef1ce963a7fa7abdf5108 (do not edit this line) */
