/* Generated By:JJTree: Do not edit this line. ASTtest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtest extends SimpleNode {
  public ASTtest(int id) {
    super(id);
  }

  public ASTtest(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d59fdc0c54c76aeccf147daecb456cb9 (do not edit this line) */
