/* Generated By:JJTree: Do not edit this line. ASTTemo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTemo extends SimpleNode {
  public ASTTemo(int id) {
    super(id);
  }

  public ASTTemo(Dot2Dot p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d50f0ddc076ea92dfdd5dd0e3af30ac (do not edit this line) */
