/* Generated By:JavaCC: Do not edit this line. Dot2DotTreeConstants.java Version 5.0 */
public interface Dot2DotTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTGRAPH = 1;
  public int JJTVOID = 2;
  public int JJTEDGE_STMT_TEMP = 3;
  public int JJTEDGE_STMT = 4;
  public int JJTATTR_SMT = 5;
  public int JJTNODE_ID = 6;
  public int JJTATTR_LIST = 7;
  public int JJTA_LIST = 8;
  public int JJTSUBGRAPH = 9;
  public int JJTTEMO = 10;
  public int JJTEDGERHS = 11;
  public int JJTPORT = 12;


  public String[] jjtNodeName = {
    "Expression",
    "Graph",
    "void",
    "Edge_stmt_temp",
    "Edge_stmt",
    "Attr_smt",
    "Node_id",
    "Attr_list",
    "A_list",
    "Subgraph",
    "Temo",
    "EdgeRHS",
    "Port",
  };
}
/* JavaCC - OriginalChecksum=ef66ccba34029ed0c5d677b00dd7db3f (do not edit this line) */
