/* Generated By:JavaCC: Do not edit this line. Dot2DotTreeConstants.java Version 5.0 */
public interface Dot2DotTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTGRAPH = 1;
  public int JJTSTMT_LIST = 2;
  public int JJTSTMT = 3;
  public int JJTNODE_STMT = 4;
  public int JJTEDGE_STMT = 5;
  public int JJTATTR_SMT = 6;
  public int JJTNODE_ID = 7;
  public int JJTATTR_LIST = 8;
  public int JJTA_LIST = 9;
  public int JJTSUBGRAPH = 10;
  public int JJTEDGERHS = 11;
  public int JJTPORT = 12;


  public String[] jjtNodeName = {
    "Expression",
    "Graph",
    "Stmt_list",
    "Stmt",
    "Node_stmt",
    "Edge_stmt",
    "Attr_smt",
    "Node_id",
    "Attr_list",
    "A_list",
    "Subgraph",
    "EdgeRHS",
    "Port",
  };
}
/* JavaCC - OriginalChecksum=b637327a8ab2c89fd8bf171019ed5377 (do not edit this line) */
