/* Generated By:JJTree&JavaCC: Do not edit this line. Dot2DotConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Dot2DotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CARDINAL = 5;
  /** RegularExpression Id. */
  int INTEGER = 6;
  /** RegularExpression Id. */
  int LF = 7;
  /** RegularExpression Id. */
  int GRAPH = 8;
  /** RegularExpression Id. */
  int STRICT = 9;
  /** RegularExpression Id. */
  int ATTR_SMT = 10;
  /** RegularExpression Id. */
  int SUBGRAPH = 11;
  /** RegularExpression Id. */
  int COMPASS_PT = 12;
  /** RegularExpression Id. */
  int NODE = 13;
  /** RegularExpression Id. */
  int ID = 14;
  /** RegularExpression Id. */
  int EDGEOP_DIRECTED = 15;
  /** RegularExpression Id. */
  int EDGEOP_UNDIRECTED = 16;
  /** RegularExpression Id. */
  int LBRACK = 17;
  /** RegularExpression Id. */
  int RBRACK = 18;
  /** RegularExpression Id. */
  int LSQBRACK = 19;
  /** RegularExpression Id. */
  int RSQBRACK = 20;
  /** RegularExpression Id. */
  int COLON = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int EQUALS = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int STRING = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\u0000\"",
    "\"#\"",
    "<INTEGER>",
    "\"\\n\"",
    "<GRAPH>",
    "\"strict\"",
    "<ATTR_SMT>",
    "\"subgraph\"",
    "<COMPASS_PT>",
    "\"node\"",
    "<ID>",
    "\"->\"",
    "\"--\"",
    "<LBRACK>",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\",\"",
    "<STRING>",
  };

}
